branches:
  only:
  - master
  - /^v\d+\.\d+\.x$/
language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.28.0
matrix:
  allow_failures:
    - rust: nightly
    - rust: 1.28.0
script:
  - cargo build --verbose --all-features
  # https://github.com/dtolnay/semver-trick/issues/4
  # - if [ $TRAVIS_RUST_VERSION = stable ]; then cargo test --verbose --all-features; fi
  - cargo check --verbose --all-features --release
