branches:
  only:
  - master
  - /^v\d+\.\d+\.x$/
language: rust
rust:
  - stable
  - beta
  - nightly-2019-11-21
  - 1.31.0
matrix:
  allow_failures:
    # - rust: nightly
    - rust: 1.31.0
script:
  - cargo build --verbose --all-features
  - cargo test --verbose --all-features
  - cargo check --verbose --all-features --release
