[package]
name = "oauth1-request"
version = "0.1.2"
authors = ["Daiki Mizukami <tesaguriguma@gmail.com>"]
license = "MIT OR Apache-2.0"
keywords = ["oauth", "oauth1"]
categories = ["authentication"]
homepage = "https://github.com/tesaguri/oauth1-request-rs"
repository = "https://github.com/tesaguri/oauth1-request-rs"
documentation = "https://docs.rs/oauth1-request/0.1.2/oauth1_request/"
description = """
Yet yet yet another OAuth 1 client library.
"""

[dependencies]
base64 = "0.9"
bitflags = "1"
hmac = "0.7"
percent-encoding = "1"
rand = "0.5"
sha-1 = "0.8"

[dev-dependencies]
hyper = "0.12"
