[package]
name = "examples"
edition = "2018"
version = "0.0.0"
authors = ["Daiki Mizukami <tesaguriguma@gmail.com>"]
publish = false

# Exclude this project from the parent workspace
# to support Cargo versions that don't understand `edition`
[workspace]

[[bin]]
name = "derive"
path = "src/derive.rs"

[[bin]]
name = "signer"
path = "src/signer.rs"

[dependencies]
bytes = "0.4"
futures-preview = { version = "0.3.0-alpha.17" }
hyper = { version = "0.13.0-a.0", git = "https://github.com/hyperium/hyper" }
oauth1-request = { version = "0.2", path = "../oauth1-request" }
oauth1-request-derive = { version = "0.2", path = "../oauth1-request-derive" }
string = "0.2"
tokio = { version = "0.2", git = "https://github.com/tokio-rs/tokio" }
