[package]
name = "examples"
edition = "2018"
version = "0.0.0"
authors = ["Daiki Mizukami <tesaguriguma@gmail.com>"]
publish = false

[[bin]]
name = "derive"
path = "src/derive.rs"

[[bin]]
name = "signer"
path = "src/signer.rs"

[dependencies]
bytes = "0.4"
futures-preview = { version = "0.3.0-alpha.17" }
hyper = "0.13.0-alpha.1"
oauth = { version = "0.3", package = "oauth1-request" }
string = "0.2"
tokio = "0.2.0-alpha.1"
